# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-25T14:21:56Z"
  labels:
    app: completion-pod
  name: completion-pod
spec:
  containers:
  - args:
    - --model-id
    - /data/starcoderbase
    - --max-total-tokens
    - "8192"
    - --max-batch-total-tokens
    - "128000"
    - --max-concurrent-requests
    - "1100"
    - --waiting-served-ratio
    - "1.7"
    image: ghcr.io/huggingface/text-generation-inference:1.0.2
    name: sharpkalam
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: home-arjun-models-host-0
  - args:
    - --prompt-file
    - /data/prompts.jsonl
    - --output-file
    - /output/out.jsonl
    - --log-file
    - /output/log.out
    - --server-url
    - http://127.0.0.1:8080/
    - --num-connections
    - "100"
    - --attempt-limit
    - "20"
    - --num-runners
    - "50"
    image: localhost/local/rs-completion-client:latest
    name: festivetaussig
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /data
      name: home-johngouwar-experiments-kubernetes-fun-host-0
    - mountPath: /output
      name: home-johngouwar-experiments-kubernetes-fun-host-1
    - mountPath: /tmp
      name: tmp-host-2
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/johngouwar/experiments/kubernetes-fun
      type: Directory
    name: home-johngouwar-experiments-kubernetes-fun-host-0
  - hostPath:
      path: /home/johngouwar/experiments/kubernetes-fun
      type: Directory
    name: home-johngouwar-experiments-kubernetes-fun-host-1
  - hostPath:
      path: /tmp
      type: Directory
    name: tmp-host-2
  - hostPath:
      path: /home/arjun/models
      type: Directory
    name: home-arjun-models-host-0
status: {}

